<?php

Class Welcome extends Controller {
    
    function __construct()
    {           
        parent::__construct();
    }  
    
    public function index()
    {  
        view_var('title', 'Welcome to Obullo !');
       
        $auth = lib('ob/Auth');
        $auth->select('user_username, user_password, user_active');
        $row = $auth->get('example@gmail.com', '123456');
        
        // echo $this->db->last_query(true);
        
        if($auth->check())
        {
            if($row->user_active == 0)
            {
                echo 'Please activate your membership.';
            }
        }

        // $auth->check('/dashboard', '/login');
        
        $auth = lib('ob/Auth');
        
        if($auth->check())
        {
            echo 'Great you are authorized to view this page !';
        }
        
        echo $auth->data('user_username');
        
        log_me('debug', '[ welcome ]: Example log who want keep log files in welcome module !');
        
        $data['var'] = 'and generated by ';
        
        view_var('body', view('view_welcome', $data));  // Set view to layout variable
        view('../layouts/welcome');                // You can include layout from /views folder if "layout" word used.
    }
    
    function hmvc()
    {
        loader::helper('ob/request');

        $data['response_a'] = request('welcome/test/1/2/3')->exec();
        $data['response_b'] = request('backend/hello/test/1/2/3')->exec();
        
        view_var('body', view('view_hmvc', $data));
        view('layouts/welcome');    // You can include layout from local folder.
    }
    
    function test($arg1 = '', $arg2 = '', $arg3 = '')
    {
        echo '<pre>Response: '.$arg1 .' - '.$arg2. ' - '.$arg3.'</pre>';
    }
     
    function task($mode = '')
    {
        if(PHP_OS != 'Linux')
        {
            exit('Please run task functionality under the linux platforms.');
        }
        
        loader::helper('ob/task');
        
        echo "<font size='2'>";
        echo "You should run this command with none true or 'false' ";
        echo "argument when you go LIVE server ! .".br().".e.g. task_run('module/controller/method', false);";
        echo br().anchor('welcome/task/help', 'Click Here to Help !');
        echo "<font>";
        
        if($mode == 'help')
        {
            task_run('start/help', true);  // use without true when you go live.
        }
        else
        {
            task_run('start/index', true); // use without true when you go live.
        }
    }
    
}

/* End of file start.php */
/* Location: .modules/welcome/controllers/welcome.php */