<?php

Class Welcome extends Controller {
    
    function __construct()
    {           
        parent::__construct();
    }         
    
    public function index()
    {         
        view_var('title', 'Welcome to Obullo !');
        
        log_me('debug', '[ welcome ]: Example log who want keep log files in welcome module !');
        
        $data['var'] = 'and generated by ';
        
        view_var('body', view('view_welcome', $data));  // Set view to layout variable
        view('layouts/welcome');                        // View func include a layout if "layouts" word used.
    }
    
    function hmvc()
    {
        loader::helper('ob/request');

        $data['response_a'] = request('welcome/test/1/2/3')->exec();
        $data['response_b'] = request('backend/hello/test/1/2/3')->exec();
        
        view_var('body', view('view_hmvc', $data));
        view('layouts/welcome');
    }
    
    function test($arg1 = '', $arg2 = '', $arg3 = '')
    {
        echo '<pre>Response: '.$arg1 .' - '.$arg2. ' - '.$arg3.'</pre>';
    }
     
    function task($mode = '')
    {
        if(PHP_OS != 'Linux')
        {
            exit('Please run task functionality under the linux platforms.');
        }
        
        loader::helper('ob/task');
        
        echo "<font size='2'>";
        echo "You should run this command with none true or 'false' ";
        echo "argument when you go LIVE server ! .".br().".e.g. task_run('module/controller/method', false);";
        echo br().anchor('welcome/task/help', 'Click Here to Help !');
        echo "<font>";
        
        if($mode == 'help')
        {
            task_run('start/help', true);  // use without true when you go live.
        }
        else
        {
            task_run('start/index', true); // use without true when you go live.
        }
    }
    
}

/* End of file start.php */
/* Location: .modules/welcome/controllers/welcome.php */